title: "JC writes"
tagline: Personal blog of Junchen Xia aka JC.
url: https://jcxia.com
baseurl: "/"
markdown: kramdown
permalink: date
timezone: Asia/Shanghai
disqus: jcxia-blog
comments: true

author:
  name: Junchen Xia
  url: https://twitter.com/jcxia43
  email: xjconlyme@gmail.com
