name: Onlimii
description: Personal blog of Junchen Xia (onlimii).
url: http://www.onlimii.com
markdown: redcarpet
# markdown: kramdown
pygments: true
paginate: 10
disqus: tiom
permalink: /blog/:year/:month/:day/:title
timezone: Asia/Shanghai

