title: "JC writes"
tagline: Personal blog of Junchen Xia, aka JC.
url: http://jcxia.com
baseurl: "/"
paginate: 1
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
# markdown: kramdown
# kramdown:
#   input: GFM
disqus: tiom
permalink: /posts/:title
timezone: Asia/Shanghai

author:
  name: Junchen Xia
  url: https://twitter.com/jcxia43
  email: xjconlyme@gmail.com
