name: Onlimii
description: Personal blog of Junchen Xia (onlimii).
url: http://www.jcxia.com
markdown: redcarpet
# markdown: kramdown
# kramdown:
#   input: GFM
paginate: 3
disqus: tiom
permalink: /blog/:year/:month/:day/:title
timezone: Asia/Shanghai

