title: "JC writes"
tagline: Personal blog of Junchen Xia, aka JC.
url: http://jcxia.com
baseurl: "/"
markdown: kramdown
permalink: /posts/:title
timezone: Asia/Shanghai
disqus: jcxia-blog

author:
  name: Junchen Xia
  url: https://twitter.com/jcxia43
  email: xjconlyme@gmail.com
