title: "JC writes"
tagline: Personal blog JC.
url: https://jcxia.com
baseurl: "/"
markdown: kramdown
permalink: "blog/:title"
timezone: Asia/Shanghai
disqus: jcxia-blog
comments: false

author:
  name: JC
  url: https://twitter.com/justcosine
